language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/phpcs --standard=PSR12 --colors -n src tests

after_script:
  - bash <(curl -s https://codecov.io/bash)
